# Generated by Django 3.0 on 2020-05-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='num_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add',
            name='num_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add',
            name='result',
            field=models.IntegerField(),
        ),
    ]
