# Generated by Django 3.0 on 2020-05-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200513_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add',
        ),
    ]
